### ISSUE TITLE
status update in FMS-endpoint should update status in FMB

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/fms-endpoint#4] opened 2012-05-23 23:30 UTC
Long-term ideal requirement: implement status update, presumably by allowing FMS to poll for status changes (with cut-off date based on FMS's last successful poll)

**Comment by BenJam** [comment] 2012-09-10 08:48
is this not /quite/ important?

**Comment by davewhiteland** [comment] 2012-09-10 12:07
It's marked as an enhancement for now, because updates can be made manually (there's a link back to the report on FMS) -- FMS now can handle updates (from the Bromley work aiui) so we could add this. Note that we anticipate FMS-endpoint also being used for problem reports that haven't come in through FMS, so it's not clear how major an aspect this will actually be.

**Comment by davewhiteland** [comment] 2012-10-02 10:53
Do this by implementing https://github.com/mysociety/fixmystreet/wiki/Open311-FMS---Proposed-differences-to-Open311

**Comment by BenJam** [comment] 2012-10-29 16:27
oh yes please.

**Comment by BenJam** [comment] 2012-10-29 16:28
dupe of #21

**Closed as completed** 2012-10-29 16:28 UTC
Labels: enhancement
